### ISSUE TITLE
How to make sure email has been sent?

### ISSUE THREAD

**Issue by HZSamir** [tiaanduplessis/react-native-email#14]
Hello,
in my use-case I need to keep a trace of all emails sent by the user (title, content etc..) using this lib one can open mail app, but how can I make sure the email has been correctly sent? That the user did not cancel or otherwise the mail was not sent because of connectivity problems?

Edit: Is there a way to programmatically send the email immediately through my own custom form?

Thank you.

**Comment by tiaanduplessis** [comment]
Unfortunately, I do not believe this is possible for this package. It is a tiny wrapper around the Linking API which is limited in the functionality it can provide.
