### ISSUE TITLE
I don't think react-native-email is working anymore!

### ISSUE THREAD

**Issue by XavierMod** [tiaanduplessis/react-native-email#22]
<img width="289" alt="Screenshot 2021-06-16 at 12 57 47" src="https://user-images.githubusercontent.com/50713842/122214833-74879b00-cea2-11eb-8a65-1621899de19c.png">

**Comment by tiaanduplessis** [comment]
Duplicate of https://github.com/tiaanduplessis/react-native-email/issues/9
