### ISSUE TITLE
Provided URL cannot be handled error

### ISSUE THREAD

**Issue by decodez** [tiaanduplessis/react-native-email#5]
handleEmail = () => {
        const to = ['tiaan@email.com', 'foo@bar.com'] // string or array of email addresses
        email(to, {
            // Optional additional arguments
            cc: ['bazzy@moo.com', 'doooo@daaa.com'], // string or array of email addresses
            bcc: 'mee@mee.com', // string or array of email addresses
            subject: 'Show how to use',
            body: 'Some body right here'
        }).catch(console.error)
    }

when using the example it gives the error

**Comment by SoftARV** [comment]
I was testing this and if you are using the iOS Simulator the linking cannot be completed because the Email app is not found in the Simulator. 
You should use the Android Emulator or a physical iOS Device.

**Comment by tiaanduplessis** [comment]
Thanks @SoftARV. @decodez does this resolve your issue?

**Comment by tiaanduplessis** [comment]
I'm closing this in the meantime. Please feel free to open the issue again if the problem persists.

**Comment by mbefokam** [comment]
I am having the same issue
