### ISSUE TITLE
Is there a way of sending PDF base64 as attachment ?

### ISSUE THREAD

**Issue by vOtto** [tiaanduplessis/react-native-email#6]
Im trying to send PDF but cant use storage from iOS, solution was to create base64  of it. is it possible with your solution ?

**Comment by Chetanspace** [comment]
same here ..

**Comment by brmk** [comment]
Hi @vOtto , did you find a way to handle it?

**Comment by brmk** [comment]
update: I use https://github.com/chirag04/react-native-mail to send emails with attachments

**Comment by tiaanduplessis** [comment]
@brmk is correct. This library is a tiny wrapper around the Linking API. https://github.com/chirag04/react-native-mail should be used for more complex requirements.
