### ISSUE TITLE
Add Image

### ISSUE THREAD

**Issue by juanriglos** [tiaanduplessis/react-native-email#8]
It's possible to add and image on the body or any other field?, thanks!

**Comment by claudioviola** [comment]
Same need here
is it possible insert HTML in the body?
I could use img tag with base64 in the `src`prop

**Comment by tiaanduplessis** [comment]
The solution suggested by @claudioviola could possibly work, but providing a first-class API for this will unfortunately not be possible. This library is a tiny wrapper around the Linking API using the `mailto` URI.
