### ISSUE TITLE
Provided URL can not be handled

### ISSUE THREAD

**Issue by pavlea** [tiaanduplessis/react-native-email#9]
Tried to send and email like in the example of your README file, but get error: Provided URL can not be handled.
https://gyazo.com/8aa2532d818885b7d8f8caf03cf82b92

**Comment by tiaanduplessis** [comment]
@pavlea on what device are you attempting to run the example?

**Comment by pavlea** [comment]
@tiaanduplessis it's an android emulator

**Comment by EscolanoGarnica** [comment]
i have the same issue, but in ios emulator, is it because ios emulator doesnt has email app?

**Comment by tiaanduplessis** [comment]
@EscolanoGarnica yes If you are using the iOS Simulator the linking cannot be completed because the Email app is not found in the Simulator.

**Comment by sallar** [comment]
Same issue happens on Android (real device) 11

**Comment by tiaanduplessis** [comment]
@sallar does it perhaps relate to the issue mentioned [here](https://github.com/tiaanduplessis/react-native-phone-call#running-on-android-sdk-30)? 

The `canOpenURL` check has been removed in v2.0.0 and is now opt in.

**Comment by efstathiosntonas** [comment]
This can be fixed by adding this to `AndroidManifest.xml`:

```xml
    <queries>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <data android:scheme="mailto" />
        </intent>
    </queries>
```

@tiaanduplessis maybe add this to README / docs?

**Comment by tiaanduplessis** [comment]
@efstathiosntonas good point. I've documented it here -> https://github.com/tiaanduplessis/react-native-email#running-on-android-sdk-30

**Comment by efstathiosntonas** [comment]
Great, thanks @tiaanduplessis!

**Comment by CptFabulouso** [comment]
@tiaanduplessis Why is in the documentation something different than what @efstathiosntonas posted? For me it's working with his, but not yours. 
Btw the site with API docs is not working

**Comment by dreamawakening** [comment]
@tiaanduplessis the docs only say to add this block:

```xml
<queries>
      <intent>
        <action android:name="android.intent.action.DIAL" />
      </intent>
</queries>
```

It doesn't mention adding what you said above in this thread (it wasn't working for me until I added this):

```xml
<queries>
    <intent>
        <action android:name="android.intent.action.VIEW" />
        <data android:scheme="mailto" />
    </intent>
</queries>
```

Therefore I suggest the docs need to be updated for this.
